x = str(input('Digite seu nome completo: ')).strip()
print(f'Analisando seu nome...')
print(f'Seu nome em maiúsculas é {x.upper()}')
print(f'Seu nome em minúsculas é {x.lower()}')
print('Seu nome tem ao todo {} letras'.format(len(''.join(x.split()))))
print('Seu nome tem ao todo {} letras'.format(len(x) - x.count(' ')))
print(f'Seu primeiro nome é {x.split()[0]} e ele tem {len(x.split()[0])} letras')
print('Seu primeiro nome é {} e ele tem {} letras'.format(x.split()[0], x.find('-')))
print(x.split())
